<?php
namespace Omnipay\AdyenApi\Message\Errors;

/**
 * Class ErrorCode
 * provide constant about error code field
 * @see https://docs.adyen.com/pages/viewpage.action?pageId=5376980
 */
class ErrorCode
{
    const UNKNOWN = 0;
    const NOT_ALLOWED = 10;
    const NO_AMOUNT_SPECIFIED = 100;
    const INVALID_CARD_NUMBER = 101;
    const UNABLE_TO_DETERMINE_VARIANT = 102;
    const CVC_IS_NOT_THE_RIGHT_LENGTH = 103;
    const BILLING_ADDRESS_PROBLEM = 104;
    const INVALID_PA_RES_FROM_ISSUER = 105;
    const THIS_SESSION_WAS_ALREADY_USED_PREVIOUSLY = 106;
    const RECURRING_IS_NOT_ENABLED = 107;
    const INVALID_BANKACCOUNT_NUMBER = 108;
    const INVALID_VARIANT = 109;
    const BANK_DETAILS_MISSING = 110;
    const INVALID_BANK_COUNTRY_CODE_SPECIFIED = 111;
    const THIS_BANK_COUNTRY_IS_NOT_SUPPORTED = 112;
    const NO_INVOICE_LINES_PROVIDED = 113;
    const RECEIVED_AN_INCORRECT_INVOICE_LINE = 114;
    const TOTAL_AMOUNT_IS_NOT_THE_SAME_AS_THE_SUM_OF_THE_LINES = 115;
    const INVALID_DATE_OF_BIRTH = 116;
    const INVALID_BILLING_ADDRESS = 117;
    const INVALID_DELIVERY_ADDRESS = 118;
    const INVALID_SHOPPER_NAME = 119;
    const SHOPPER_EMAIL_IS_MISSING = 120;
    const SHOPPER_REFERENCE_IS_MISSING = 121;
    const PHONE_NUMBER_IS_MISSING = 122;
    const THE_PHONE_NUMBER_SHOULD_BE_MOBILE = 123;
    const INVALID_PHONE_NUMBER = 124;
    const INVALID_RECURRING_CONTRACT_SPECIFIED = 125;
    const BANK_ACCOUNT_OR_BANK_LOCATION_ID_NOT_VALID_OR_MISSING = 126;
    const ACCOUNT_HOLDER_MISSING = 127;
    const CARD_HOLDER_MISSING = 128;
    const EXPIRY_DATE_INVALID = 129;
    const REFERENCE_MISSING = 130;
    const BILLING_ADDRESS_PROBLEM_CITY = 131;
    const BILLING_ADDRESS_PROBLEM_STREET = 132;
    const BILLING_ADDRESS_PROBLEM_HOUSE_NUMBER_OR_NAME = 133;
    const BILLING_ADDRESS_PROBLEM_COUNTRY = 134;
    const BILLING_ADDRESS_PROBLEM_STATE_OR_PROVINCE = 135;
    const FAILED_TO_RETRIEVE_OPEN_INVOICE_LINES = 136;
    const INVALID_AMOUNT_SPECIFIED = 137;
    const UNSUPPORTED_CURRENCY_SPECIFIED = 138;
    const RECURRING_REQUIRES_SHOPPER_EMAIL_AND_SHOPPER_REFERENCE = 139;
    const INVALID_EXPIRY_MONTH_OR_EXPIRY_YEAR_OR_BEFORE_NOW = 140;
    const INVALID_EXPIRY_MONTH_OR_EXPIRY_YEAR = 141;
    const BANK_NAME_OR_BANK_LOCATION_NOT_VALID_OR_MISSING = 142;
    const SUBMITTED_TOTAL_I_DEAL_MERCHANT_RETURN_URL_LENGTH_IS__BUT_MAX_SIZE_IS_FOR_THIS_REQUEST = 143;
    const INVALID_START_MONTH_OR_START_YEAR_OR_IN_THE_FUTURE = 144;
    const INVALID_ISSUER_COUNTRYCODE = 145;
    const INVALID_SOCIAL_SECURITY_NUMBER = 146;
    const DELIVERY_ADDRESS_PROBLEM_CITY = 147;
    const DELIVERY_ADDRESS_PROBLEM_STREET = 148;
    const DELIVERY_ADDRESS_PROBLEM_HOUSE_NUMBER_OR_NAME = 149;
    const DELIVERY_ADDRESS_PROBLEM_COUNTRY = 150;
    const DELIVERY_ADDRESS_PROBLEM_STATE_OR_PROVINCE = 151;
    const INVALID_NUMBER_OF_INSTALLMENTS = 152;
    const INVALID_CVC = 153;
    const NO_ADDITIONAL_DATA_SPECIFIED = 154;
    const NO_ACQUIRER_SPECIFIED = 155;
    const NO_AUTHORISATION_MID_SPECIFIED = 156;
    const NO_FIELDS_SPECIFIED = 157;
    const REQUIRED_FIELD_NOT_SPECIFIED = 158;
    const INVALID_NUMBER_OF_REQUESTS = 159;
    const NOT_ALLOWED_TO_STORE_PAYOUT_DETAILS = 160;
    const INVALID_IBAN = 161;
    const INCONSISTENT_IBAN = 162;
    const INVALID_BIC = 163;
    const AUTO_CAPTURE_DELAY_INVALID_OR_OUT_OF_RANGE = 164;
    const MANDATE_ID_DOES_NOT_MATCH_PATTERN = 165;
    const AMOUNT_NOT_ALLOWED_FOR_THIS_OPERATION = 166;
    const ORIGINAL_PSP_REFERENCE_REQUIRED_FOR_THIS_OPERATION = 167;
    const AUTHORISATION_CODE_REQUIRED_FOR_THIS_OPERATION = 168;
    const GENERATION_DATE_REQUIRED_BUT_MISSING = 170;
    const UNABLE_TO_PARSE_GENERATION_DATE = 171;
    const ENCRYPTED_DATA_USED_OUTSIDE_OF_VALID_TIME_PERIOD = 172;
    const UNABLE_TO_LOAD_PRIVATE_KEY_FOR_DECRYPTION = 173;
    const UNABLE_TO_DECRYPT_DATA = 174;
    const UNABLE_TO_PARSE_JSON_DATA = 175;
    const INVALID_SHOPPER_REFERENCE = 180;
    const INVALID_SHOPPER_EMAIL = 181;
    const INVALID_SELECTED_BRAND = 182;
    const INVALID_RECURRING_CONTRACT = 183;
    const INVALID_RECURRING_DETAIL_NAME = 184;
    const INVALID_ADDITIONAL_DATA = 185;
    const MISSING_ADDITIONAL_DATA_FIELD = 186;
    const INVALID_ADDITIONAL_DATA_FIELD = 187;
    const INVALID_PSP_ECHO_DATA = 188;
    const INVALID_SHOPPER_STATEMENT = 189;
    const INVALID_SHOPPER_IP = 190;
    const NO_PARAMS_SPECIFIED = 191;
    const INVALID_FIELD = 192;
    const BIN_DETAILS_NOT_FOUND_FOR_THE_GIVEN_CARD_NUMBER = 193;
    const BILLING_ADDRESS_MISSING = 194;
    const NO_INVOICE_PROJECT_PROVIDED = 600;
    const NO_INVOICE_BATCH_PROVIDED = 601;
    const NO_CREDITOR_ACCOUNT_SPECIFIED = 602;
    const NO_PROJECT_CODE_SPECIFIED = 603;
    const NO_CREDITOR_ACCOUNT_FOUND = 604;
    const NO_PROJECT_FOUND = 605;
    const UNABLE_TO_CREATE_INVOICE_PROJECT = 606;
    const INVOICE_BATCH_ALREADY_EXISTS = 607;
    const UNABLE_TO_CREATE_INVOICE_BATCH = 608;
    const INVOICE_BATCH_VALIDITY_PERIOD_EXCEEDED = 609;
    const NO_DUNNING_CONFIGURATION_FOUND = 610;
    const INVALID_DUNNING_CONFIGURATION = 611;
    const ERROR_WHILE_STORING_DEBTOR = 690;
    const ERROR_WHILE_STORING_INVOICE = 691;
    const ERROR_WHILE_CHECKING_IF_INVOICE_ALREADY_EXISTS_FOR_CREDITOR_ACCOUNT = 692;
    const ERROR_WHILE_SEARCHING_INVOICES = 693;
    const NO_INVOICE_CONFIGURATION_CONFIGURED_FOR_CREDIT_ACCOUNT = 694;
    const INVALID_INVOICE_CONFIGURATION_CONFIGURED_FOR_CREDIT_ACCOUNT = 695;
    const NO_METHOD_SPECIFIED = 700;
    const SERVER_COULD_NOT_PROCESS_REQUEST = 701;
    const PROBLEM_PARSING_REQUEST = 702;
    const CONTRACT_NOT_FOUND = 800;
    const TOO_MANY_PAYMENT_DETAILS_DEFINED = 801;
    const INVALID_CONTRACT = 802;
    const PAYMENT_DETAIL_NOT_FOUND = 803;
    const FAILED_TO_DISABLE = 804;
    const RECURRING_DETAIL_REFERENCE_NOT_AVAILABLE_FOR_PROVIDED_RECURRING_CONTRACT = 805;
    const NO_APPLICABLE_CONTRACT_TYPES_LEFT_FOR_THIS_PAYMENT_METHOD = 806;
    const INVALID_MERCHANT_ACCOUNT = 901;
    const SHOULDN_T_HAVE_GOTTEN_HERE_WITHOUT_A_REQUEST = 902;
    const INTERNAL_ERROR = 903;
    const UNABLE_TO_PROCESS = 904;
    const PAYMENT_DETAILS_ARE_NOT_SUPPORTED = 905;
    const INVALID_REQUEST_ORIGINAL_PSP_REFERENCE_IS_INVALID_FOR_THIS_ENVIRONMENT = 906;
    const US_PAYMENT_DETAILS_ARE_NOT_SUPPORTED = 907;
    const INVALID_REQUEST = 908;
    const INVALID_ACQUIRER_ACCOUNT = 950;
    const CONFIGURATION_ERROR_ACQUIRER_IDENTIFICATION = 951;
    const CONFIGURATION_ERROR_ACQUIRER_PASSWORD = 952;
    const CONFIGURATION_ERROR_API_KEY = 953;
    const CONFIGURATION_ERROR_REDIRECT_URL = 954;
    const CONFIGURATION_ERROR_ACQUIRER_ACCOUNT_DATA = 955;
    const CONFIGURATION_ERROR_CURRENCY_CODE = 956;
    const CONFIGURATION_ERROR_TERMINAL_ID = 957;
    const CONFIGURATION_ERROR_SERIAL_NUMBER = 958;
    const CONFIGURATION_ERROR_PASSWORD = 959;
    const CONFIGURATION_ERROR_PROJECT_ID = 960;
    const CONFIGURATION_ERROR_MERCHANT_CATEGORY_CODE = 961;
    const CONFIGURATION_ERROR_MERCHANT_NAME = 962;
    const INVALID_COMPANY_REGISTRATION_NUMBER = 963;
    const INVALID_COMPANY_NAME = 964;
    const MISSING_COMPANY_DETAILS = 965;
    const CONFIGURATION_ERROR_PRIVATE_KEY_ALIAS = 966;
    const CONFIGURATION_ERROR_PUBLIC_KEY_ALIAS = 967;
    const CARD_NUMBER_CANNOT_BE_SPECIFIED_FOR_INCONTROL_VIRTUAL_CARD_REQUESTS = 1000;
    const RECURRING_NOT_ALLOWED_FOR_INCONTROL_VIRTUAL_CARD_REQUESTS = 1001;
    const INVALID_AUTHORISATION_TYPE_SUPPLIED = 1002;

    public static $messageList = array(
        0 => 'Unknown',
        10 => 'Not allowed',
        100 => 'No amount specified',
        101 => 'Invalid card number',
        102 => 'Unable to determine variant',
        103 => 'CVC is not the right length',
        104 => 'Billing address problem',
        105 => 'Invalid paRes from issuer',
        106 => 'This session was already used previously',
        107 => 'Recurring is not enabled',
        108 => 'Invalid bank account number',
        109 => 'Invalid variant',
        110 => 'BankDetails missing',
        111 => 'Invalid BankCountryCode specified',
        112 => 'This bank country is not supported',
        113 => 'No InvoiceLines provided',
        114 => 'Received an incorrect InvoiceLine',
        115 => 'Total amount is not the same as the sum of the lines',
        116 => 'Invalid date of birth',
        117 => 'Invalid billing address',
        118 => 'Invalid delivery address',
        119 => 'Invalid shopper name',
        120 => 'ShopperEmail is missing',
        121 => 'ShopperReference is missing',
        122 => 'PhoneNumber is missing',
        123 => 'The PhoneNumber should be mobile',
        124 => 'Invalid PhoneNumber',
        125 => 'Invalid recurring contract specified',
        126 => 'Bank Account or Bank Location Id not valid or missing',
        127 => 'Account holder missing',
        128 => 'Card Holder Missing',
        129 => 'Expiry Date Invalid',
        130 => 'Reference Missing',
        131 => 'Billing address problem (City)',
        132 => 'Billing address problem (Street)',
        133 => 'Billing address problem (HouseNumberOrName)',
        134 => 'Billing address problem (Country)',
        135 => 'Billing address problem (StateOrProvince)',
        136 => 'Failed to retrieve OpenInvoiceLines',
        137 => 'Invalid amount specified',
        138 => 'Unsupported currency specified',
        139 => 'Recurring requires shopperEmail and shopperReference',
        140 => 'Invalid expiryMonth[1..12] / expiryYear[>2000], or before now',
        141 => 'Invalid expiryMonth[1..12] / expiryYear[>2000]',
        142 => 'Bank Name or Bank Location not valid or missing',
        143 => 'Submitted total iDeal merchantReturnUrl length is {0}, but max size is {1} for this request',
        144 => 'Invalid startMonth[1..12] / startYear[>2000], or in the future',
        145 => 'Invalid issuer country code',
        146 => 'Invalid social security number',
        147 => 'Delivery address problem (City)',
        148 => 'Delivery address problem (Street)',
        149 => 'Delivery address problem (HouseNumberOrName)',
        150 => 'Delivery address problem (Country)',
        151 => 'Delivery address problem (StateOrProvince)',
        152 => 'Invalid number of installments',
        153 => 'Invalid CVC',
        154 => 'No additional data specified',
        155 => 'No acquirer specified',
        156 => 'No authorisation mid specified',
        157 => 'No fields specified',
        158 => 'Required field {0} not specified',
        159 => 'Invalid number of requests',
        160 => 'Not allowed to store Payout Details',
        161 => 'Invalid iban',
        162 => 'Inconsistent iban',
        163 => 'Invalid bic',
        164 => 'Auto-capture delay invalid or out of range',
        165 => 'MandateId does not match pattern',
        166 => 'Amount not allowed for this operation',
        167 => 'Original pspReference required for this operation',
        168 => 'AuthorisationCode required for this operation',
        170 => 'Generation Date required but missing',
        171 => 'Unable to parse Generation Date',
        172 => 'Encrypted data used outside of valid time period',
        173 => 'Unable to load Private Key for decryption',
        174 => 'Unable to decrypt data',
        175 => 'Unable to parse JSON data',
        180 => 'Invalid shopperReference',
        181 => 'Invalid shopperEmail',
        182 => 'Invalid selected brand',
        183 => 'Invalid recurring contract',
        184 => 'Invalid recurring detail name',
        185 => 'Invalid additionalData',
        186 => 'Missing additionalData field',
        187 => 'Invalid additionalData field',
        188 => 'Invalid pspEchoData',
        189 => 'Invalid shopperStatement',
        190 => 'Invalid shopper IP',
        191 => 'No params specified',
        192 => 'Invalid field {0}',
        193 => 'Bin Details not found for the given card number',
        194 => 'Billing address missing',
        600 => 'No InvoiceProject provided',
        601 => 'No InvoiceBatch provided',
        602 => 'No creditorAccount specified',
        603 => 'No projectCode specified',
        604 => 'No creditorAccount found',
        605 => 'No project found',
        606 => 'Unable to create InvoiceProject',
        607 => 'InvoiceBatch already exists',
        608 => 'Unable to create InvoiceBatch',
        609 => 'InvoiceBatch validity period exceeded',
        610 => 'No dunning configuration found',
        611 => 'Invalid dunning configuration',
        690 => 'Error while storing debtor',
        691 => 'Error while storing invoice',
        692 => 'Error while checking if invoice already exists for creditorAccount',
        693 => 'Error while searching invoices',
        694 => 'No Invoice Configuration configured for creditAccount',
        695 => 'Invalid Invoice Configuration configured for creditAccount',
        700 => 'No method specified',
        701 => 'Server could not process request',
        702 => 'Problem parsing request',
        800 => 'Contract not found',
        801 => 'Too many PaymentDetails defined',
        802 => 'Invalid contract',
        803 => 'PaymentDetail not found',
        804 => 'Failed to disable',
        805 => 'RecurringDetailReference not available for provided recurring-contract',
        806 => 'No applicable contractTypes left for this payment-method',
        901 => 'Invalid Merchant Account',
        902 => 'Shouldn\'t have gotten here without a request!',
        903 => 'Internal error',
        904 => 'Unable To Process',
        905 => 'Payment details are not supported',
        906 => 'Invalid Request: Original pspReference is invalid for this environment!',
        907 => 'US Payment details are not supported',
        908 => 'Invalid request',
        950 => 'Invalid AcquirerAccount',
        951 => 'Configuration Error (acquirerIdentification)',
        952 => 'Configuration Error (acquirerPassword)',
        953 => 'Configuration Error (apiKey)',
        954 => 'Configuration Error (redirectUrl)',
        955 => 'Configuration Error (AcquirerAccountData)',
        956 => 'Configuration Error (currencyCode)',
        957 => 'Configuration Error (terminalId)',
        958 => 'Configuration Error (serialNumber)',
        959 => 'Configuration Error (password)',
        960 => 'Configuration Error (projectId)',
        961 => 'Configuration Error (merchantCategoryCode)',
        962 => 'Configuration Error (merchantName)',
        963 => 'Invalid company registration number',
        964 => 'Invalid company name',
        965 => 'Missing company details',
        966 => 'Configuration Error (privateKeyAlias)',
        967 => 'Configuration Error (publicKeyAlias)',
        1000 => 'Card number cannot be specified for Incontrol virtual card requests',
        1001 => 'Recurring not allowed for Incontrol virtual card requests',
        1002 => 'Invalid Authorisation Type supplied',
    );
}
